[build]
xargo = true
build-std = true
default-target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
xargo = true
build-std = true
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main"
#pre-build = [
#    "curl -fsSL https://rpm.nodesource.com/setup_16.x | bash -",
#    "curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo",
#    "rpm --import https://dl.yarnpkg.com/rpm/pubkey.gpg",
#    "yum -y install openssl-devel node yarn"
#]
pre-build = [
    "curl -fsSL https://deb.nodesource.com/setup_16.x | bash -",
    "curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add ",
    "echo \"deb https://dl.yarnpkg.com/debian/ stable main\" | tee /etc/apt/sources.list.d/yarn.list",
    "apt-get update",
    "apt-get -y install --no-install-recommends yarn libssl-dev nodejs"
]
env = { passthrough = ["SQLX_OFFLINE=true"] }