targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "aarch64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" }
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = [
    "https://github.com/cultpony/sqlx-adapter.git",
    "https://github.com/philomena-dev/comrak",
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
unsound = "deny"
ignore = [
    "RUSTSEC-2020-0145", # heapless vuln from sentry crates
    "RUSTSEC-2021-0145", # from atty which isn't in prod
    "RUSTSEC-2021-0141", # used only in dev/test
    "RUSTSEC-2020-0071", # time crate is currently not patchable
    "RUSTSEC-2022-0006", # textile support is deprecated
    "RUSTSEC-2022-0013", # also via textile crate
]

[licenses]
unlicensed = "allow"
allow-osi-fsf-free = "both"
copyleft = "deny"
default = "warn"
unused-allowed-license = "warn"
deny = []
allow = [
    "0BSD",
    "AGPL-3.0", # todo, remove those dependencies
    "Apache-2.0",
    "CC0-1.0",
    "GPL-3.0", # this is camo-url, we can ignore that license
    "MIT-0",
    "MIT",
    "MPL-2.0",
    "Unicode-DFS-2016",
    "zlib-acknowledgement",
]

[[licenses.exceptions]]
allow = ["LicenseRef-Proprietary"]
name = "tiberius-server"

[[licenses.exceptions]]
allow = ["LicenseRef-Proprietary"]
name = "tiberius-search"

[[licenses.exceptions]]
allow = ["LicenseRef-Proprietary"]
name = "tiberius-models"

[[licenses.exceptions]]
allow = ["LicenseRef-Proprietary"]
name = "tiberius-jobs"

[[licenses.exceptions]]
allow = ["LicenseRef-Proprietary"]
name = "tiberius-dependencies"

[[licenses.exceptions]]
allow = ["LicenseRef-Proprietary"]
name = "tiberius-common-html"

[[licenses.exceptions]]
allow = ["LicenseRef-Proprietary"]
name = "tiberius-core"

[bans]
multiple-versions = "deny"

[[bans.skip]]
name = "axum"

[[bans.skip]]
name = "axum-core"

[[bans.skip]]
name = "axum_database_sessions"

[[bans.skip]]
name = "bcrypt"

[[bans.skip]]
name = "cookie"

[[bans.skip]]
name = "matchit"

[[bans.skip]]
name = "tower-cookies"

[[bans.skip]]
name = "aho-corasick" # textile issue

[[bans.skip]]
name = "base64"

[[bans.skip]]
name = "tower-http"

[[bans.skip]]
name = "axum-extra"

[[bans.skip]]
name = "cfg-if"

[[bans.skip]]
name = "clap_lex"

[[bans.skip]]
name = "lazy_static"

[[bans.skip]]
name = "memchr"

[[bans.skip]]
name = "nix"

[[bans.skip]]
name = "nom"

[[bans.skip]]
name = "percent-encoding"

[[bans.skip]]
name = "regex"

[[bans.skip]]
name = "rustc_version"

[[bans.skip]]
name = "semver"

[[bans.skip]]
name = "thread_local" # coming from textile

[[bans.skip]]
name = "url" # another one frmo textile

[[bans.skip]]
name = "utf8-ranges"

[[bans.skip]]
name = "uuid"

[[bans.skip]]
name = "md-5"

[[bans.skip]]
name = "miniz_oxide"

[[bans.skip]]
name = "parking_lot"

[[bans.skip]]
name = "parking_lot_core"

[[bans.skip]]
name = "time"

[[bans.skip]]
name = "spin"

[[bans.skip]]
name = "sha3"

[[bans.skip]]
name = "sha2"

[[bans.skip]]
name = "sha-1"

[[bans.skip]]
name = "regex-syntax"

[[bans.skip]]
name = "itoa"

[[bans.skip]]
name = "idna"

[[bans.skip]]
name = "hmac"

[[bans.skip]]
name = "hashbrown"

[[bans.skip]]
name = "half"

[[bans.skip]]
name = "generic-array"

[[bans.skip]]
name = "digest"

[[bans.skip]]
name = "crypto-mac"

[[bans.skip]]
name = "clap"

[[bans.skip]]
name = "block-buffer"

[[bans.skip]]
name = "blake2"

[[bans.skip]]
name = "ahash"

[[bans.skip]]
name = "spin"

[[bans.skip]]
name = "syn"