version: "3"
services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./local-data/postgres:/var/lib/postgresql/data
