[package]
name = "tiberius-dependencies"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.5", features = ["http2", "headers"] }
axum-extra = { version = "^0.3", features = ["typed-routing", "cookie-lib", "cookie-signed", "cookie-private", "async-read-body"] }
axum_database_sessions = "4.0.2"
axum_sessions_auth = "3.0.0"
axum-flash = "0.4.0"
axum_csrf = "0.4.1"
tower = "^0.4"
http = "^0.2"
totp-rs = "2"
headers = "0.3"
mime = "0.3"
rust-embed = { version = "6.4.0", features = ["compression", "axum", "tokio"] }
maud = { version = "*", features = ["axum"] }
tempfile = "3"
serde_qs = { version = "0.9.2", features = ["axum"] }
http-serde = "1.1.0"
ammonia = "3.2.0"
once_cell = "1.13.0"
async-once-cell = "0.4.2"
moka = { version = "0.9", features = ["future"] }
chrono-humanize = "0.2.1"
blake2 = "0.10.4"
hex = "0.4.3"
sentry = { version = "0.27.0", features = ["tracing", "anyhow", "tower", "panic", "contexts"] }
sqlx-adapter = { git = "https://github.com/cultpony/sqlx-adapter.git", features = ["postgres", "runtime-tokio-rustls"], default-features = false }
casbin = "2.0.9"
axum-strangler = "0.3.0"
regex = "1.5.4"
lazy_static = "1.4"
serde_urlencoded = "0.7.1"