[package]
name = "tiberius-common-html"
version = "0.1.0"
edition = "2021"
license = "LicenseRef-Proprietary"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maud = { version = "*", features = ["axum"] }