[package]
name = "tiberius-jobs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.9", features = ["attributes", "tokio1"] }
async-trait = "0.1.50"
base64 = "0.13"
bcrypt = "0.10.0"
chrono = "0.4.19"
csp = "0.1.0"
either = { version = "1.6.1", features = ["serde"] }
envy = "0.4"
hex = "0.4.3"
image = "0.23"
itertools = "0.10.1"
lazy_static = "1.4"
maud = { git = "https://github.com/mbr/maud", branch = "mbr/rocket-0.5", features = ["rocket"] }
new_mime_guess = "3.0"
paseto = "2.0.0"
rand = "0.8.3"
regex = "1.5.3"
reqwest = { version = "0.11", features = ["json", "socks", "cookies"] }
ring = "0.16.20"
rocket = { version = "0.5.0-rc.1", features = ["secrets", "uuid", "json", "msgpack"] }
rust-embed = { version = "6.1", features = ["compression"] }
securefmt = "0.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.1"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.9.5"
sqlx = { version = "0.5.9", features = ["postgres", "chrono", "time", "macros", "json", "runtime-tokio-rustls", "offline", "migrate"] }
sqlxmq = { git = "https://github.com/cultpony/sqlxmq.git", default-features = false, features = ["runtime-tokio-rustls"] }
thiserror = "1.0.30"
tiberius-core = { path = "../tiberius-core" }
tiberius-models = { path = "../tiberius-models" }
tokio = { version = "1.10", features = ["full"] }
tokio-cron-scheduler = "0.2.1"
tracing = "0.1.29"
url = { version = "2.2", features = ["serde"] }
uuid = "0.8.1"

[features]
default = ["all-jobs"]
all-jobs = ["cleanup-jobs", "online-jobs", "reindex-jobs", "processing-jobs"]
stable-jobs = ["cleanup-jobs"]

cleanup-jobs = ["job_cleanup_sessions"]
online-jobs = ["job_picarto_tv"]
reindex-jobs = ["job_reindex_images", "job_reindex_tags"]
processing-jobs = ["job_process_image"]

job_cleanup_sessions = []
job_picarto_tv = []
job_process_image = ["job_reindex_images"]
job_reindex_images = []
job_reindex_tags = []
