[package]
name = "tiberius-core"
version = "0.1.0"
edition = "2021"

[build-dependencies]
change-detection = "1.2.0"

[dependencies]
async-std = { version = "1.9", features = ["attributes", "tokio1"] }
async-trait = "0.1.52"
base64 = "0.13"
bcrypt = "0.10.0"
chrono = "0.4.19"
casbin = "2.0.7" # needs tobe 2.0.8 until sqlxmq is replaced or updated
csp = "0.1.0"
either = { version = "1.6.1", features = ["serde"] }
envy = "0.4"
hex = "0.4.3"
image = "0.23"
itertools = "0.10.1"
lazy_static = "1.4"
tracing = "0.1.29"
maud = { git = "https://github.com/mbr/maud", branch = "mbr/rocket-0.5", features = ["rocket"] }
new_mime_guess = "3.0"
paseto = "2.0.0"
rand = "0.8.3"
regex = "1.5.3"
reqwest = { version = "0.11", features = ["json", "socks", "cookies"] }
ring = "0.16.20"
rocket = { version = "0.5.0-rc.1", features = ["secrets", "uuid", "json", "msgpack"] }
rust-embed = { version = "6.1", features = ["compression"] }
securefmt = "0.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.1"
serde_derive = "1.0"
serde_json = "1.0"
sqlx = { version = "0.5.9", features = ["postgres", "chrono", "time", "macros", "json", "runtime-tokio-rustls", "offline", "migrate", "uuid"] }
sqlx-adapter = { version = "0.4.2", default-features = false, features = ["runtime-tokio-rustls", "postgres"] }
thiserror = "1.0.30"
tiberius-models = { path = "../tiberius-models" }
tokio = { version = "1.10", features = ["full"] }
url = { version = "2.2", features = ["serde"] }
uuid = "0.8.1"
erlang-term = "0.1.1"
anyhow = "1.0"

[dev-dependencies]
openssl = { version = "0.10.36", features = ["vendored", "v111"] }
