# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
#
# While our "example" application has the platform-specific code,
# for simplicity we are compiling and testing everything on the Ubuntu environment only.
# For multi-OS testing see the `cross.yml` workflow.

on:
  push:
      branches:
        - main
  pull_request:
      branches:
        - main

name: Run Tests on Push/PR

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    services:
      mailhog:
        image: mailhog/mailhog:v1.0.0
        ports:
          - 1025:1025
          - 8025:8025
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: github_actions
          POSTGRES_USER: github_actions
          POSTGRES_DB: philomena_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Cache Setup
        uses: Swatinem/rust-cache@v2

      - name: Cache Target/ Dir
        uses: actions/cache@v3
        with:
          path: |
            target
          key: ${{ runner.os }}-test

      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: |
            **/package-lock.json
            **/yarn.lock

      - run: |
          cd res/assets
          npm install -g yarn
          yarn install
          NODE_ENV=production yarn deploy

      - name: Install cargo sqlx cli
        uses: baptiste0928/cargo-install@v1
        with:
          crate: sqlx-cli
          version: "0.6"

      - name: Run cargo sqlx migrate
        run: |
          export TIBERIUS_PREBUILT_ASSETS=YES
          export DATABASE_URL="postgres://github_actions:github_actions@localhost:5432/philomena_db"
          cargo sqlx migrate run

      - name: Cargo Check
        run:  |
          export TIBERIUS_PREBUILT_ASSETS=YES
          export DATABASE_URL="postgres://github_actions:github_actions@localhost:5432/philomena_db"
          cargo check --workspace

      - name: Build Workspace
        run:  |
          export TIBERIUS_PREBUILT_ASSETS=YES
          export DATABASE_URL="postgres://github_actions:github_actions@localhost:5432/philomena_db"
          cargo build --workspace

      - name: Run tests
        run:  |
          export TIBERIUS_PREBUILT_ASSETS=YES
          export DATABASE_URL="postgres://github_actions:github_actions@localhost:5432/philomena_db"
          cargo test --workspace --no-fail-fast

      - name: Check for cargo-deny lints
        uses: EmbarkStudios/cargo-deny-action@v1
        continue-on-error: true
